---
abstract: 'report memory leaks (objects) per request'
author:
  - 'Ruslan Zakirov <ruz@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MasonX::LeakGuard::Object
name: MasonX-LeakGuard-Object
no_index:
  directory:
    - inc
requires:
  Data::Dumper: 0
  Devel::LeakGuard::Object: 0
  HTML::Mason::Plugin: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
